### ISSUE TITLE
alwaysOn / neverOn not working

### ISSUE THREAD

**Issue by gerhard-lechner** [nswilhelm/jquery-map-trifecta#1]
Hi! First of all, thank you for your awesome script!

I've used Maphilight before and need to make some areas on my map "alwaysOn" by adding `data-maphilight="{alwaysOn:true}"` to the `<area>` element. It actually works in the first place, but as soon as i hover the alwaysOn element and leave it with the cursor, the area will become invisible.

This can easily be reproduced in the demo script at http://jsfiddle.net/k6pukgLd/ just by adding `{alwaysOn:true}` to the initial call of `$("img[usemap]").mapTrifecta();`.

Also neverOn seems to have no effect.

**Comment by abertranb** [comment]
Hi @codeworks the problem is related when you do onmouseout, I solved only for alwaysOn

https://github.com/3iPunt/jquery-map-trifecta/blob/master/js/jquery.map-trifecta.js

Basically check when is alwasOn

```
                    if (!area_options.alwaysOn) {
                        clear_canvas(canvas);
                    }
```
But still we have an issue with neverOn

Best regards
