### ISSUE TITLE
Image misalignment

### ISSUE THREAD

**Issue by Caroga** [nswilhelm/jquery-map-trifecta#3]
Hi,
I've been trying to correctly implement this wonderfull combination of plugins, but it's not working that well for me.
I currently have a image with a few rectangles I need to be constantly highlighted. 
After page rendering, the image moves to the center of it's container (due to the margin: auto) , while the canvas (holding the rectangles) stays on the left, creating a gap around 300px's of where the rectangles should have been placed.

Any idea on what I need to do to correct this ? 

Kind regards,
Caroga

**Comment by nswilhelm** [comment]
Can you send me a jsfiddle.net demonstrating this problem?

**Comment by Caroga** [comment]
Sure, will make one now. Sorry for the delay in response, been afk due to illness.

**Comment by Caroga** [comment]
JSFiddle: https://jsfiddle.net/z2rLowsv/3/
I find that the image responsiveness is also not working.
![misalignmentissue](https://cloud.githubusercontent.com/assets/4005934/21496446/f8943bdc-cc1e-11e6-8eaf-aa0eb994d5ad.PNG)

When hovering with your mouse over the box where the rectangle should've been drawn, you'll notice the box actually is there. The red box however is misaligned.

**Comment by nswilhelm** [comment]
The problems with the plugin currently seem to be:
1. Only **jquery-1.11.0.js** seems to work with it.
2. Area tag needs **data-mapid** attribute. Which is bad programming on my part...er, sry
3. **alwaysOn** will not work until the window is resized, which I don't fully understand why.

Here's as close as I can get: https://jsfiddle.net/z2rLowsv/9/
if you can get past these with some hacking around the script it will work, but it'll take me some time to actually implement the needed changes

hope this helps

**Comment by Caroga** [comment]
Hi, thank you for responding and taking a look into the matter.

1. I cannot downgrade my jQuery lib to match the working version. I did however thought it was working though? 
2. Not a problem, will add this.
3. Is there a way to bypass this by triggering a window resize by js?

Thanks for the help so far.

**Comment by nswilhelm** [comment]
That's a good question. I know you can trigger the resize event but an actual resize might be blocked for security reasons.
