### ISSUE TITLE
href not working

### ISSUE THREAD

**Issue by damngraphic** [nswilhelm/jquery-map-trifecta#4]
Hi, I've been using this plugin for a while and it's been great for what I needed, but now I need to make an area link to a website but it doesn't seem to work. Is there a way to make the url work properly?

`<area href="http://www.google.com/" alt="google" data-mapid="9" shape="poly" coords="393,594,471,520,482,512,472,488,457,480,441,476,424,475,407,475,392,478,383,482,368,482,356,482,348,486,339,490,332,495,327,510,329,526,341,546,352,564,366,582,384,594" class="{fillColor:'04606A',strokeColor: '0392B7'}">`

**Comment by nswilhelm** [comment]
You could try adding an onclick to the area tag.

<area onclick="window.open('http://www.google.com', '_self');" href="#" alt="google" data-mapid="9" shape="poly" coords="393,594,471,520,482,512,472,488,457,480,441,476,424,475,407,475,392,478,383,482,368,482,356,482,348,486,339,490,332,495,327,510,329,526,341,546,352,564,366,582,384,594" class="{fillColor:'04606A',strokeColor: '0392B7'}">

**Comment by nswilhelm** [comment]
You could try adding an onclick to the area tag.

`<area onclick="window.open('http://www.google.com', '_self');" href="#" alt="google" data-mapid="9" shape="poly" coords="393,594,471,520,482,512,472,488,457,480,441,476,424,475,407,475,392,478,383,482,368,482,356,482,348,486,339,490,332,495,327,510,329,526,341,546,352,564,366,582,384,594" class="{fillColor:'04606A',strokeColor: '0392B7'}">`
